### ISSUE TITLE
Questionable recommendations for typescript configuration

### ISSUE THREAD

**Issue by philfontaine** [quasarframework/quasar-starter-kit#106]
**Describe the bug**

This issue is more of a discussion than a bug.

Recommendations are often useful for people who are unsure about there decision or just don't know what they are doing, and should therefore suggest the "best-practice" choice in some way.

When choosing typescript, this starter kit recommends to use either the composition-api or the class based API. While I do agree that they will probably provide a better typescript experience, I don't think they are reasonable **recommended** choices. (BTW I am using the composition-api myself)

### Composition API
1. It isn't recommended to use this in production. From the [README](https://github.com/vuejs/composition-api):
> We do not recommend using this package for production yet at this stage.

2. This will be an advanced API in Vue 3, and will not be the recommended default API, as stated [in the adoption strategy](https://composition-api.vuejs.org/#adoption-strategy)
> The API will be positioned as an advanced feature, since the problems it aims to address appear primarily in large scale applications. We do not intend to overhaul the documentation to use it as the default. Instead, it will have its own dedicated section in the docs.

### Class based API

This is a community plugin, and I don't know how many people are actually using this, but it is certainly not the majority, which one again does not seem like a good "recommended" choice to me.

### Option API

I think this will probably provide the poorest typescript experience (definitely not that bad), but at least it will be inline with Vue's recommendations.

**Comment by philfontaine** [comment]
I may be wrong on the class based API, as vuejs doc does mention it : https://vuejs.org/v2/guide/typescript.html#Class-Style-Vue-Components so that may seem like a legitimate default.

**Comment by IlCallo** [comment]
`vue-class-component` is maintained by Vue core team and will be so even when Vue3 comes.
`vue-property-decorator` is community-based. As are many of packages used in open source :)
Together they were the best choice for Vue + TS until Composition API.

Composition API has been created **specifically** to address Class API shortcomings related to TS and has been described many times as the best solution for Vue + TS developer experience.
`@vue/composition-api` is the Vue2 port of the new API. It may be in `0.x`, but so is `axios` and many others open source packages used in production every day around the globe.


Note that both Class API and Composition API are proposed only if you ask for a TS codebase, which means you **want** the best-in-class support for TS. Otherwise normal Options API is provided.

Currently you get the best Vue + TS developer experience, in order, with Composition API > Class API > Options API.
This is why the first two are the recommended ones

**Comment by philfontaine** [comment]
These are valid points, just wanted to make sure that these were carefully thought decisions.

Cheers

**Comment by IlCallo** [comment]
No problem, feel free to come to our Discord server to discuss further :)
