### ISSUE TITLE
Outdated dependency warnings

### ISSUE THREAD

**Issue by brylie** [quasarframework/quasar-starter-kit#111]
When scaffolding a new project with the Quaser CLI, there are several warnings about outdated dependencies:

```
warning @quasar/app > webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning Resolution field "@babel/parser@7.7.5" is incompatible with requested version "@babel/parser@^7.9.6"
warning @quasar/app > webpack-dev-server > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning @quasar/app > node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @quasar/app > node-sass > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning Resolution field "@babel/parser@7.7.5" is incompatible with requested version "@babel/parser@^7.8.6"
warning Resolution field "@babel/parser@7.7.5" is incompatible with requested version "@babel/parser@^7.9.6"
warning @quasar/app > @quasar/babel-preset-app > @babel/runtime-corejs2 > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning @quasar/app > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning @quasar/app > @quasar/babel-preset-app > babel-plugin-transform-imports > babel-types > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
```

**To Reproduce**
I am following the steps in the [Quasar CLI Installation guide](https://quasar.dev/quasar-cli/installation).

**Expected behavior**
Core dependencies for the Quasar CLI would be kept up to date.

**Platform (please complete the following information):**
OS: Ubuntu Linux
Node: 12
NPM:
Yarn: 1.22.4

**Comment by rstoenescu** [comment]
Hi,

In an ideal world, updating any of those dependencies (except for the ones in webpack-dev-server, webpack and node-sass for which their owners are responsible) would not completely break your app.

Treat them as they are. Warnings. With our guarantee that your apps are safe. We keep the deps up to date (including the before mentioned webpack, webpack-dev-server and node-sass) with few exceptions. For example, upgrading to corejs 3 is not a small feat and not for the reasons that you might think of. You upgrade that and a lot of the nodejs packages out there will simply not work -- so it's out of our control since their owners must supply compatibility first. But what is in our control is to ensure that you hit "quasar dev" or "quasar build" and everything simply works with whatever dependencies you put into your app. Those versions don't affect your development in any way.
