### ISSUE TITLE
Starter Kits Capacitor iOS builds in simulator but times out on device

### ISSUE THREAD

**Issue by hwlmatt** [quasarframework/quasar-starter-kit#112]
**Describe the bug**
When building for device, the starter kit (fresh, nothing added, etc) correctly builds for the simulator, but times out on the device with a blank, white screen.
 Xcode console says:
``⚡️  WebView failed provisional navigation
⚡️  Error: The request timed out.``

**To Reproduce**
`$ quasar create myproject`
follow prompts. my answers:

- css: **Sass**
- import strategy: **Auto import**
- features: **ESLint, Vuex, Axios, Vue-i18n**
- ESLint preset: **Standard**
- `npm install`
- `quasar mode add capacitor`
- `quasar dev -m capacitor -T ios`

then in Xcode: 
select account for team under Signing & Certificates

Build for simulator (iPhone 11) --- all works as expected
Build for plugged in device (iPhone) -- the issue above.

**Expected behavior**
for the starter kit to build as it does on simulator.

**Platform (please complete the following information):**
OS: Mac 10.15.4
Node: v12.13.0
NPM: 6.14.4
Device: iPhone X
iOS: 13.4.1

**Additional context**
I have gone through the docs, but perhaps I missed something glaring. Apologies if so.
combing Google results for the error kept ending in the issue being about connecting to external resource

Fuller XCode console message:
`Reachable via Cellular
APP ACTIVE
SplashScreen.hideSplash: SplashScreen was automatically hidden after default timeout. You should call SplashScreen.hide() as soon as your web app is loaded (or increase the timeout). Read more at https://capacitor.ionicframework.com/docs/apis/splash-screen/#hiding-the-splash-screen
⚡️  WebView failed provisional navigation
⚡️  Error: The request timed out.`

Cheers and thanks for any guidance

**Comment by rstoenescu** [comment]
Hi,

You need to do "quasar build -m capacitor -T ios" for the production build. Otherwise XCode will still run the development build which connects to your machine's IP.

**Comment by hwlmatt** [comment]
ahhhhhhh wow.
and `quasar build -m capacitor -T ios -ide` opens xcode...
man, I need coffee. :) 
many thanks!

**Comment by sms-harc** [comment]
Hi - any ideas why I would encounter the same issue noted above (attempting connect to local machine IP for production Capacitor build) - I am for certain building with the proper "quasar build -m capacitor -T ios" build command.

I'm running latest Quasar version and the only thing I've altered in my project was to update the capacitor-core and capacitor-ios packages to latest versions (2.4.6). I've since downgraded them to prior 2.1.2 versions but still the same issue. Have tried repeated builds and have been diagnosing for a couple of hours now with no luck...

XCODE console output is:
`Loading network plugin
2021-02-28 16:26:45.207277-0800 STEPSTOOL[30788:16831719] CAPKeyboard: resize mode - native
⚡️  Loading app at http://192.168.1.125:8081...
2021-02-28 16:26:45.275389-0800 STEPSTOOL[30788:16831719] WF: === Starting WebFilter logging for process STEPSTOOL
2021-02-28 16:26:45.275437-0800 STEPSTOOL[30788:16831719] WF: _userSettingsForUser mobile: {
    filterBlacklist =     (
    );
    filterWhitelist =     (
    );
    restrictWeb = 1;
    useContentFilter = 0;
    useContentFilterOverrides = 0;
    whitelistEnabled = 0;
}
2021-02-28 16:26:45.275490-0800 STEPSTOOL[30788:16831719] WF: _WebFilterIsActive returning: NO
APP ACTIVE
Reachable via WiFi
2021-02-28 16:26:45.826578-0800 STEPSTOOL[30788:16831719] [Process] 0x103817a18 - [pageProxyID=6, webPageID=7, PID=30789] WebPageProxy::didFailProvisionalLoadForFrame: frameID = 3, domain = NSURLErrorDomain, code = -1004
⚡️  WebView failed provisional navigation
⚡️  Error: Could not connect to the server.
SplashScreen.hideSplash: SplashScreen was automatically hidden after default timeout. You should call `SplashScreen.hide()` as soon as your web app is loaded (or increase the timeout). Read more at https://capacitor.ionicframework.com/docs/apis/splash-screen/#hiding-the-splash-screen
`
