### ISSUE TITLE
Quasar Create Issue in Windows

### ISSUE THREAD

**Issue by julianfrank** [quasarframework/quasar-starter-kit#131]
**Describe the bug**
As per Instruction i installed quasar and tried to created my first app and it gives an error

**To Reproduce**
1. Install Quasar using 
```
npm install -g @quasar/cli
```

2. It Installs and even show info
```
$ quasar info
Operating System        Windows_NT(10.0.17134) - win32/x64
NodeJs                  12.13.0
Global packages
  NPM                   6.12.0
  yarn                  Not installed
  @quasar/cli           1.1.0
  cordova               Not installed
```
3. Now I try to create my first app and bug comes up

```
quasar create www

  ___
 / _ \ _   _  __ _ ___  __ _ _ __
| | | | | | |/ _` / __|/ _` | '__|
| |_| | |_| | (_| \__ \ (_| | |
 \__\_\\__,_|\__,_|___/\__,_|_|



-  Downloading Quasar starter kit
  Quasar CLI · Failed to download repo quasarframework/quasar-starter-kit#master: unable to get local issuer certificate

```
Quasar CLI · Failed to download repo quasarframework/quasar-starter-kit#master: unable to get local issuer certificate

**Expected behavior**
Things should have worked as per online guide

**Screenshots**
cli trace given above

**Platform (please complete the following information):**
OS: Windows 10
Node: 12.13
NPM:6.12
Yarn:nope
Browsers:Chrome
iOS:nope
Android:nope
Electron:nope

**Additional context**
As a complete Newbie , I should see this!

**Comment by IlCallo** [comment]
Hi @julianfrank, Quasar CLI downloads the starter kit from this repo master branch, your problem seems to be related to that download step as something fails while initiating the secure connection due to a certificate problem.
Have you googled the error online?

I also suggest you to use `yarn` instead of `npm` as the latter could lead to undeterministic behaviour.

Please check your environment as the problem almost certainly relies there and is out of our reach.
I'll close the issue, but please follow up if you find a solution or evidence the error is actually on our side.

**Comment by macran** [comment]
I run into the same problem. It is possible for me that reset  git ssh key.
`ssh-keygen -t rsa -C "youremail@google.com"`,please replace  "youremail@google.com" with your real EMAIL address that sign up in github.  hope to help you.
