### ISSUE TITLE
ESLint Standard - PropType not found in ‘vue‘ (and other types)

### ISSUE THREAD

**Issue by intelliBrain** [quasarframework/quasar-starter-kit#160]
**Describe the bug**
just created a brand new quasar v2 project (SCSS, TypeScript, ESLint Standard, Axios, Composition API) enabled. however, quasar CLI always shows some strange eslint errors (see screenshot).

the issue only occurs when ESLint Standard is selected on "quasar create". no problems with ESLint Prettier... 

additional info & screenshots provided in discord:
https://discord.com/channels/415874313728688138/807654245640962059/874670423890096168
https://discord.com/channels/415874313728688138/807654245640962059/874674923153555498

**To Reproduce**
1) run „quasar create testproj“ with options: SCSS, TypeScript, ESLint Standard, Axios, Composition API
2) Quasar CLI does its magic…
3) …final eslint step fails with errors (see screenshots in discord, links above) when ESLint Standard is selected (however, no issue if ESLint Prettier was selected)

**Expected behavior**
Quasar CLI completes without errors

**Screenshots**
![Screenshot](https://cdn.discordapp.com/attachments/807654245640962059/874674920225931324/Quasar_-_eslint_errors2.png)

**Platform (please complete the following information):**
OS: Windows 10
Node: 14.17.4
NPM: 7.19.1
Yarn: 1.22.5
Browsers: -
iOS: - 
Android: -
Electron: -

**Additional context**

**Comment by IlCallo** [comment]
This is done because we define custom rules on Standard ESLint preset instead of relying on the preset configs
You can either:

- remove all custom `import` rules except `no-unresolved` and follow [this guide](https://github.com/import-js/eslint-plugin-import#typescript)
- disable `import/named` rule as [it's not meant to work with TS](https://github.com/import-js/eslint-plugin-import/pull/1726)

We'll probably remove the `import/named` rule definition for TS generated projects, thanks for reporting

**Comment by intelliBrain** [comment]
disable the rule worked for me. thanks!
