### ISSUE TITLE
i18n: switch language programmatically

### ISSUE THREAD

**Issue by fansanelli** [quasarframework/quasar-starter-kit#51]
Hello,
I am playing with the i18n plugin and I think it would be useful to have a way to switch language programmatically, the only way I found is the next one:

**plugins/i18n.js**
```
import Vue from 'vue'
import VueI18n from 'vue-i18n'
import messages from 'src/i18n'

Vue.use(VueI18n)
const i18n = new VueI18n({
  locale: 'en-us',
  fallbackLocale: 'en-us',
  messages
})

export default ({ app }) => {
  // Set i18n instance on app
  app.i18n = i18n
}

export { i18n }
```

then I can do:

```
import { i18n } from '../plugins/i18n'
...
if (lang !== i18n.locale) {
  i18n.locale = lang
}
```
Mind that this will not redraw like:
```
this.$i18n.locale = lang
```
What do you think about this approach? I can do a PR if it's not completely wrong.
Cheers,
Francesco

**Comment by rstoenescu** [comment]
Hi,

Yes, this is the way to do it. Would you be so kind to create a PR for it? If you'd be so kind, a docs update would be good too.

Thank you!
- Razvan

**Comment by fansanelli** [comment]
Humble ping, gents. Could someone confirm this will be ok for SSR too?

**Comment by nothingismagick** [comment]
But I am really trying to get the best of ALL worlds for SSR that goes the following steps:
- zero: guard against "inappropriate / unavailable" locale names in cookie / browser pref / route
- first: cookie preference
- next: browser pref / setting
- last: route based :locale token

For extra credit, I also switch the $q.i18n with the same hook and am exporting a watcher and loader via a global mixin.

I am using a lazy loading (one locale at a time) approach, because for huge projects you just do not want to load 15 locales with several hundred strings at a time ... Just, no.

**Comment by fansanelli** [comment]
Tbh, I don't have to do SSR in my projects, but I found that the store plugin was broken for me after latest changes... So I thought that this commit could lead to the breakage of the SSR context. If it works for you, please consider merging the patch

**Comment by nothingismagick** [comment]
I'll have to test it, but won't get to it until the end of next week. SRY

**Comment by fansanelli** [comment]
gentle ping. Is this patch ok as is?

**Comment by yusufkandemir** [comment]
It is now possible to do so. It's implemented in [this commit](https://github.com/quasarframework/quasar-starter-kit/commit/7a2e8337ab92d8614deeea1556f41aaa74a95e5d) by @rstoenescu using @fansanelli's suggestions.

**Comment by rstoenescu** [comment]
Yep. Closing.
Not only the new approach is better, it is recommended.
